version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: parking_db
    restart: always
    # network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: parking-backend
    # network_mode: "host"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
